### ISSUE TITLE
Expert Profile "Social Media" view does not describe Github link

### ISSUE THREAD

**Issue by steve-ochoa** [steve-ochoa/osu_cs_361_longbourn#31]
There is no way of knowing that the Github profile link/repositories hover popup exists by just looking at an Expert Profile. 

LinkedIn is displayed, but nothing is displayed to denote that the first link is Github-related. Also, there is no information communicated to the user to let them know that they can hover-over to see repositories.

![Screen Shot 2020-11-24 at 2 45 12 PM](https://user-images.githubusercontent.com/8741807/100160038-b9df6f00-2e63-11eb-82ae-16ba42ac128d.png)

**Comment by contip** [comment]
addressed in: 09fdd6e2d3114e5e3a7d329ed83b554a2d945e05 and 3797e6e7a35a714f09464b00ab441b4c2fce66c0

link title and usernames added for github and linkedin
popup functionality explained

![image](https://user-images.githubusercontent.com/55963118/100930013-7b2a6400-34b6-11eb-8941-eb1fd32e13ec.png)
